#+include: back.org
#+TITLE: 阿里C++研发工程师实习(淘系技术)
#+SETUPFILE: latexcss/latexcss.theme

* 一面
** DONE 已通过

CLOSED: <2022-03-15 Tue> ~ 1hour

感谢面试官

** 总体感受
面我的面试官比较注重学习历程。

里面有些问题我讲了很多，然后自己往外拓展了很多，再加上前面我结合项目说心得说了很多，导致面试官没问多少问题。

** 项目
1. 你对编程有啥理解？
2. 拿你的一个项目为例，你有什么和编程相关的心得，有没有和软件工程有关的心得？（版本控制、规范注释、谷歌C++代码规范等等）（讲了很多，感觉面试官比较满意）
3. 你是怎么校正倾斜文字的？（Hough变换和Radon变换）
4. 印象最深的项目

** 基础知识
*** C++
1. new/delete和malloc/free的区别
2. 一个类A有两个int型数据成员，还有两个成员函数，sizeof(A)是多少？
3. 如果两个数据成员声明为static呢？
4. 如果两个成员函数是虚函数呢？
5. 类B继承类A，B自己有个int型数据成员，sizeof(B)？（内存对齐）
6. C和C++的区别
7. 智能指针

*** 计网
1. TCP/UDP区别
2. DNS是啥

*** OS
1. 线程和协程

** 算法题
1.找出两个数组里的相同数字，可重复（unordered\under{}map）

** 反问
1. 面试表现
2. C++工程师实习岗位，具体干什么
3. 是否有转正机会


* DONE 二面

CLOSED: <2022-03-28 Mon>

一二面相隔时间较长是因为我一开始没做笔试直接一面，一面通过的第二天通知的，必须完成笔试才能安排二面，因此等了一个多周。

** 自我介绍

** 项目
*** 协程库
对着代码提问和回答。面试官提到了注释（docString）的书写。着重问了有栈协程的内联汇编部分的代码（保存寄存器、切换栈指针、恢复寄存器）、独立栈的保存位置、和操作系统分配的栈的关系。
无栈协程是如何实现的。
然后问了感想和收获。

** 反问
总结下来，面试官说通过对项目细节的提问，能看出设计和工程方面的能力，也能反应代码水平。

* 总结
不知道阿里其它部门的其它岗位怎么样，我面试的是淘系C++研发工程师，感觉非常看重软件工程的实践能力，也就是项目。项目要有技术点，适当复杂一些，要能体现出你的学习能力和编码能力。

面试官说没有技术面了，如果通过下轮就是HR面。


* DONE HR面

SCHEDULED: <2022-04-01 Fri>

主要问了在校经历，反问问了实习期和转正相关的。总共7min。听他们说有可能是HR想挂你，否则不会只面7min且很着急地第二天安排加面，猜测理由是HC不足。因为二面面试官告诉我，他和一面面试官的面评都不错。

* DONE 交叉面

SCHEDULED: <2022-04-02 Sat>

面试官一看就是大佬，后来谷歌了下是淘系P9。

让我介绍项目然后他会提问，然后问了些C++基础知识，会问应用场景，感觉比前两面难。
