#+TITLE: Humble Room on Mt. Takao - Main Page
#+LATEX_COMPILER: xelatex
#+LATEX_CLASS: elegantpaper
#+OPTIONS: prop:t
* Humble Room on Mt. Takao
This github pages is a site to publish some of my ideas. There used to be a blog, unfortunately due to some trivials, it had been shutdown. I'll put on my new articles here and try to re-upload some of my articles written in the past. 
** About me
I'm a SCUT undergraduate majored in CS.
No publications currently.
I'm working on a research of pedestrian detection & domain adaptation, also interested in programming languages (C++/Rust/Lisp/...) and computer architecture.
I'm short of knowledge but insisting on learning. 
** Index
1. [[./lisparse/lisparse.html][Enum of Rust used in Lisp interpreter]]
2. If you are working with Rust or Clojure, maybe you can check my emacs configuration: [[https://github.com/kabu1204/.emacs.d][kabu1204/.emacs.d]]
3. [[./local-elpa-mirror/local-elpa-mirror.html][Local ELPA mirror]]
4. [[./rlisp/rlisp.html][a better Lisp interpreter in Rust]]
5. [[./timi.html][腾讯IEG-天美L1-游戏客户端开发实习面经（已offer）]]
6. [[./bytedance_sz.html][字节跳动-内容安全-后端开发实习面经（已offer）]]
7. [[./ali.html][阿里-淘系技术部-C++研发工程师实习面经（HR面被释放）]]
** Schedules
My Schedules:[[./agenda.html][agenda]]
** Contact me
EMAIL: [[mailto:yuchengye.eric.cy@gmail.com][yuchengye.eric.cy@gmail.com]]
